version: '3.8'

services:
  frontend:
    image: node:20-alpine
    ports: ["5173:5173"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: >
      sh -c "npm create vite@latest . -- --template react-ts &&
             npm install &&
             npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/db_name
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db_name
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data: